name: github actions

on:
  push:
    branches:
      - master

jobs:
  My-Deploy-Job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hello world print 
        run: echo "hello World!"
        