name: github actions

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hello world print 
        run: echo "hello World!"
        
      - name: 여러 명령어 문장 작성 
        run: |
          echo "Good"
          echo "Morning"

      - name: github action 자체에 저장된 변수사용
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: GITHUB USER VALUES SETTINGS 
        run: | 
          echo ${{secrets.ASSET_SETTINGS}}
          echo ${{secrets.APP_SETTINGS}}